apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-12-14T21:01:53Z"
  generation: 1
  labels:
    app: odin-validation-balance
  name: odin-validation-balance
  namespace: default
  resourceVersion: "2851781"
  uid: 90a02894-b8b4-4c4a-82e5-bb2fa6adb77f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: odin-validation-balance
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: odin-validation-balance
    spec:
      containers:
        - image: 589696708747.dkr.ecr.sa-east-1.amazonaws.com/odin-validation-balance:master-04b7762f-1639686912
          imagePullPolicy: IfNotPresent
          name: odin-validation-balance
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: MONGO_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_ROOT_PASSWORD
            - name: MONGO_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: MONGO_DATABASE_URL
            - name: MONGO_CONFIGMAP_USER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: MONGO_CONFIGMAP_USER
            - name: MONGO_CONFIGMAP_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: MONGO_CONFIGMAP_PASSWORD
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2021-12-14T21:01:57Z"
      lastUpdateTime: "2021-12-14T21:01:57Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-12-14T21:01:53Z"
      lastUpdateTime: "2021-12-14T21:01:57Z"
      message: ReplicaSet "odin-validation-balance-65bc6bcfff" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
