apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    MONGO_ROOT_USERNAME: root
    MONGO_ROOT_PASSWORD: aWgweHBWZzR1cA==
    MONGO_ROOT_DATABASE: 180.0.214.83:27017/transaction?authSource=admin&authMechanism=SCRAM-SHA-1
