--------------------------------------------------------
-- Archivo creado  - lunes-noviembre-29-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CK_ALERT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "STRATOS_MX_TRANS"."CK_ALERT_SEQ"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 945011 CACHE 100 NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CK_AUTHID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "STRATOS_MX_TRANS"."CK_AUTHID_SEQ"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 41304 CACHE 100 NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CK_ALERT_ERROR_DETAIL
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_ALERT_ERROR_DETAIL" 
   (	"ERROR_COUNTER_NU" NUMBER(15,0), 
	"SERV_EXEC_STATUS_TS" TIMESTAMP (6), 
	"DAY_PART_ID" DATE GENERATED ALWAYS AS (TO_DATE(TO_CHAR("SERV_EXEC_STATUS_TS",'YYYY-MM-DD'),'YYYY-MM-DD')) VIRTUAL , 
	"ADDITIONAL_ERROR_INF" VARCHAR2(4000)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_ALERT_SERVICE_TECH_ERROR
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_ALERT_SERVICE_TECH_ERROR" 
   (	"ERROR_COUNTER_NU" NUMBER(15,0), 
	"SERV_EXEC_STATUS_TS" TIMESTAMP (6), 
	"DAY_PART_ID" DATE GENERATED ALWAYS AS (TO_DATE(TO_CHAR("SERV_EXEC_STATUS_TS",'YYYY-MM-DD'),'YYYY-MM-DD')) VIRTUAL , 
	"ERROR_LEVEL" VARCHAR2(1), 
	"THREAD_ID" VARCHAR2(50), 
	"LOGGER_ID" VARCHAR2(50), 
	"TRACE_ID" VARCHAR2(16), 
	"SPAN_ID" VARCHAR2(16), 
	"PARENT_SPAN_ID" VARCHAR2(16), 
	"ENTITY_ID" VARCHAR2(4), 
	"SERVICE_ID" VARCHAR2(30), 
	"AUTHORISATION_ID" VARCHAR2(19), 
	"SERVICE_POD_ID" VARCHAR2(50), 
	"SERVER_NAME" VARCHAR2(15), 
	"EXEC_ENVIRONMENT_ID" VARCHAR2(10), 
	"ERROR_CODE" VARCHAR2(5), 
	"ERROR_DESC" VARCHAR2(500), 
	"SERVICE_IMPACT_IN" VARCHAR2(1)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_AMH_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" 
   (	"AUTHORISATION_ID" VARCHAR2(29), 
	"SCHEME_ID" VARCHAR2(3), 
	"PMI_ID" VARCHAR2(50), 
	"SERV_LOG_TS" TIMESTAMP (6), 
	"SCHM_MSG_CODE" VARCHAR2(8), 
	"SCHM_PROCESS_CD" VARCHAR2(8), 
	"ACMS_TRN_CD" VARCHAR2(3), 
	"SCHM_TRANS_DATETIME" VARCHAR2(12), 
	"SCHM_STAN_NU" NUMBER(*,0), 
	"SCHM_ACQ_ID" VARCHAR2(11), 
	"SCHM_RESPONSE_CD" VARCHAR2(8), 
	"ACMS_RESPONSE_CD" VARCHAR2(3), 
	"SCHM_DATA_ENTRY_MODE" VARCHAR2(40), 
	"NETWORK_ID" VARCHAR2(4), 
	"ORIGINAL_AUTH_ID" VARCHAR2(29), 
	"SCHM_SETTL_AMOUNT" NUMBER(15,2), 
	"SCHM_SETTL_CURRENCY" VARCHAR2(3), 
	"SCHM_LOCAL_AMOUNT" NUMBER(15,2), 
	"SCHM_LOCAL_CURRENCY" VARCHAR2(3), 
	"SCHM_BILLING_AMOUNT" NUMBER(15,2), 
	"SCHM_BILLING_CURRENCY" VARCHAR2(3), 
	"ACMS_AUTH_AMOUNT" NUMBER(15,2), 
	"SCHM_INCOM_MATCHING_KEY" VARCHAR2(100), 
	"SCHM_AUTH_CODE" VARCHAR2(6), 
	"TERMINAL_ID" VARCHAR2(16), 
	"COMMERCE_ID" VARCHAR2(20), 
	"MSG_DATA" VARCHAR2(4000), 
	"CHANNEL_ID" VARCHAR2(8), 
	"SERV_EXCEPTION_CD" VARCHAR2(3), 
	"SERV_EXCEPTION_TX" VARCHAR2(250), 
	"SCHM_PROCESSED_FLAG" VARCHAR2(1), 
	"SCHM_TRANSACTION_STATUS" VARCHAR2(1), 
	"CONSOLIDATED_FLAG" VARCHAR2(1), 
	"REQUEST_TYPE_FLAG" VARCHAR2(1), 
	"ACMS_DATA_ENTRY_MODE" VARCHAR2(13) DEFAULT NULL, 
	"FINANCIAL_FLAG" VARCHAR2(1), 
	"RESOLVER_ID" VARCHAR2(3), 
	"ADV_SCHEME_RESPONSE_CD" VARCHAR2(8), 
	"ADV_SCHEME_REASON_CD" VARCHAR2(7), 
	"AUTH_ADDITIONAL_DATA" VARCHAR2(50), 
	"SCHM_TXN_EXECUTION_SEC_NU" NUMBER(*,0) DEFAULT 0, 
	"SCRIPT_STATUS" VARCHAR2(1), 
	"RPLC_SCHM_LOCAL_AMOUNT" NUMBER(15,2), 
	"RPLC_SCHM_BILLING_AMOUNT" NUMBER(15,2), 
	"MCC" VARCHAR2(4), 
	"POS_COUNTRY_CODE" VARCHAR2(3), 
	"ADQ_COUNTRY_CODE" VARCHAR2(3), 
	"COMMERCE_NAME" VARCHAR2(80), 
	"TERM_CITY_LOC" VARCHAR2(80), 
	"POS_POSTAL_CODE" VARCHAR2(50), 
	"SCHM_FRAUD_INDICATOR" VARCHAR2(65), 
	"AVS_VAL_RES" VARCHAR2(1), 
	"TRANSACTION_CODE" VARCHAR2(4), 
	"CONNECTION_ID" VARCHAR2(8), 
	"SCHM_RETRIEVAL_REF_NUM" VARCHAR2(50), 
	"ENTITY" VARCHAR2(4), 
	"FLOW" VARCHAR2(200), 
	"SI_AUTHORISATION_ID" VARCHAR2(29), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_AMH_AUDIT_NET
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT_NET" 
   (	"AUTHORISATION_ID" VARCHAR2(29), 
	"SCHEME_ID" VARCHAR2(3), 
	"SCHM_MSG_CODE" VARCHAR2(8), 
	"SCHM_ACQ_ID" VARCHAR2(11), 
	"SCHM_RESPONSE_CD" VARCHAR2(8), 
	"ACMS_RESPONSE_CD" VARCHAR2(3), 
	"ACMS_TRN_CD" VARCHAR2(3), 
	"RTS_ADQ" VARCHAR2(30), 
	"SCHM_TRANS_DATETIME" VARCHAR2(12), 
	"SCHM_STAN_NU" NUMBER(*,0), 
	"MSJ_INITIATOR" VARCHAR2(10), 
	"SCHM_TRANSACTION_STATUS" VARCHAR2(1), 
	"CHANNEL_ID" VARCHAR2(8), 
	"PHISICAL_CHANNEL_ID" VARCHAR2(8), 
	"SCHM_START_DATE" TIMESTAMP (6), 
	"SCHM_END_DATE" TIMESTAMP (6), 
	"PREVIOUS_STATUS_CONN" VARCHAR2(1), 
	"NEW_STATUS_CONN" VARCHAR2(1), 
	"MSJ_ADITIONAL_DATA" VARCHAR2(200), 
	"ENTITY" VARCHAR2(4) DEFAULT '0014'
   ) ;
--------------------------------------------------------
--  DDL for Table CK_AUTH_ORCHESTRATOR_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_AUTH_ORCHESTRATOR_AUDIT" 
   (	"ENTITY" VARCHAR2(4), 
	"SCHEME_ID" VARCHAR2(3), 
	"AUTHORISATION_ID" VARCHAR2(29) DEFAULT ' ', 
	"SI_AUTHORISATION_ID" VARCHAR2(29), 
	"PMI_ID" VARCHAR2(50), 
	"INT_MTI" VARCHAR2(4), 
	"SERV_LOG_TS" TIMESTAMP (6), 
	"TRN_TYPE_CD" VARCHAR2(8), 
	"ORIGINAL_AUTH_ID" VARCHAR2(29), 
	"PREV_AUTH_ID" VARCHAR2(29), 
	"TRN_AMOUNT" NUMBER(15,2), 
	"TRN_CURRENCY" VARCHAR2(3), 
	"TRN_TIMESTAMP" TIMESTAMP (6), 
	"ORCH_TRN_STATUS" VARCHAR2(1), 
	"DEST_TRANSACTION_STATUS" VARCHAR2(1), 
	"FVS_TRANSACTION_STATUS" VARCHAR2(1), 
	"SI_TRANSACTION_STATUS" VARCHAR2(1), 
	"AUTHORISED_AMOUNT" NUMBER(15,2), 
	"AUTH_CODE" VARCHAR2(6), 
	"ADV_RESP_CODE" VARCHAR2(3), 
	"RESPONSE_CD" VARCHAR2(3), 
	"DEST_INT_RESPCODE" VARCHAR2(3), 
	"FVS_INT_RESPCODE" VARCHAR2(3), 
	"SI_INT_RESPCODE" VARCHAR2(3), 
	"DUPLICATE_CONTROL_IND" VARCHAR2(1), 
	"FVS_MESSAGE_TAG" VARCHAR2(6), 
	"DEST_INT_RESOLVER" VARCHAR2(3), 
	"FVS_INT_RESOLVER" VARCHAR2(29), 
	"ORCH_INT_RESOLVER" VARCHAR2(50), 
	"ALLOW_WITHOUT_LIMITS" VARCHAR2(1), 
	"LIMITS_BYPASSED" VARCHAR2(1), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_AUTHORISATION_RULES_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_AUTHORISATION_RULES_AUDIT" 
   (	"AUTHORISATION_ID" VARCHAR2(29), 
	"PMI_ID" VARCHAR2(50), 
	"INPUT_MESSAGE" VARCHAR2(500), 
	"APPLIED_RULE_NAME" VARCHAR2(50), 
	"APPLIED_CRITERIA" VARCHAR2(1000), 
	"RESPONSE_CODE" VARCHAR2(3), 
	"SIMULATION_MODE" VARCHAR2(1), 
	"SERV_LOG_TS" TIMESTAMP (6), 
	"SERV_EXCEPTION_CD" VARCHAR2(3), 
	"SERV_EXCEPTION_TX" VARCHAR2(250), 
	"BUSINESS_EXCEPTION_TX" VARCHAR2(250), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_BALANCES
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_BALANCES" 
   (	"ENTITY" VARCHAR2(4), 
	"ACCOUNT_ID" VARCHAR2(40), 
	"LEDGER_BALANCE" NUMBER(15,2), 
	"AVAILABLE_BALANCE" NUMBER(15,2), 
	"UNPROCESSED_AMOUNT" NUMBER(15,2), 
	"BILLING_CURRENCY" VARCHAR2(3), 
	"LAST_UPDATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"DB_CR_IND" VARCHAR2(1), 
	"UPDATE_ORIGIN" VARCHAR2(50), 
	"REV_UNPROCESSED_AMOUNT" NUMBER(15,2)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_CONNECTION_LOG
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_CONNECTION_LOG" 
   (	"CONN_LOG_TS" TIMESTAMP (6), 
	"SCHEME_ID" VARCHAR2(3), 
	"CHANNEL_ID" VARCHAR2(8), 
	"CONNECTION_ID" VARCHAR2(8), 
	"ACTION_TYPE_IND" VARCHAR2(1), 
	"CONNECTION_MODE" VARCHAR2(2), 
	"ENDPOINT_DIR" VARCHAR2(50), 
	"ENDPOINT_PORT" NUMBER(*,0), 
	"ACMS_BRIDGE_ID" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_CRYPTO_BUSINESS_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_CRYPTO_BUSINESS_AUDIT" 
   (	"AUTHORISATION_ID" VARCHAR2(29), 
	"CRYPTO_FUNCTION" VARCHAR2(3), 
	"SERV_LOG_TS" TIMESTAMP (6), 
	"ENTITY_ID" VARCHAR2(4), 
	"REQUEST_TYPE_FLAG" VARCHAR2(1), 
	"PMI_ID" VARCHAR2(50), 
	"PMI_PSN" VARCHAR2(3), 
	"CHANNEL_ID" VARCHAR2(8), 
	"CRYPTO_RULE_CD" VARCHAR2(4), 
	"CRYPTO_CRIT_CODE_EMV" VARCHAR2(4), 
	"CRYPTO_CRIT_CODE_CUSTOMER" VARCHAR2(4), 
	"CRYPTO_CRIT_CODE_PMI" VARCHAR2(4), 
	"ACMS_TRN_CD" VARCHAR2(3), 
	"ACMS_DATA_ENTRY_MODE" VARCHAR2(13), 
	"EMV_AMOUNT" VARCHAR2(12), 
	"EMV_CASHB_AMOUNT" VARCHAR2(12), 
	"EMV_COUNTRY_CODE" VARCHAR2(4), 
	"EMV_TVR" VARCHAR2(10), 
	"EMV_CURRENCY_CODE" VARCHAR2(4), 
	"EMV_TRANS_DATE" VARCHAR2(6), 
	"EMV_TRANS_TYPE" VARCHAR2(2), 
	"EMV_RND_NUMBER" VARCHAR2(8), 
	"EMV_APL_INT_PROF" VARCHAR2(4), 
	"EMV_ATC" VARCHAR2(4), 
	"EMV_IAD" VARCHAR2(56), 
	"EMV_CVR" VARCHAR2(12), 
	"EMV_ARQC" VARCHAR2(16), 
	"EMV_LAST_ATC" NUMBER(*,0), 
	"CUSTOMER_PIN_TRIES" NUMBER(*,0), 
	"CUSTOMER_PINBLOCK_FORMAT" VARCHAR2(2), 
	"PMI_CVV_TRIES" NUMBER(*,0), 
	"PMI_CVV2_TRIES" NUMBER(*,0), 
	"CRYPTO_EMV_ARQC_VAL_IN" VARCHAR2(1), 
	"CRYPTO_EMV_ATC_VAL_IN" VARCHAR2(1), 
	"CRYPTO_CUSTOMER_PIN_VAL_IN" VARCHAR2(1), 
	"CRYPTO_PMI_CVV_VAL_IN" VARCHAR2(1), 
	"CRYPTO_PMI_CVV2_VAL_IN" VARCHAR2(1), 
	"CRYPTO_CUSTOMER_CAVV_VAL_IN" VARCHAR2(1), 
	"CRYPTO_CUSTOMER_HMAC_VAL_IN" VARCHAR2(1), 
	"CRYPTO_EMV_CVR_RULE_CD" VARCHAR2(3), 
	"CRYPTO_EMV_TVR_RULE_CD" VARCHAR2(3), 
	"CRYPTO_EMV_ARPC" VARCHAR2(16), 
	"CRYPTO_EMV_ARC" VARCHAR2(6), 
	"CRYPTO_RESPONSE_CD" VARCHAR2(8), 
	"ACMS_RESPONSE_CD" VARCHAR2(3), 
	"CRYPTO_TRANSACTION_STATUS" VARCHAR2(1), 
	"SERV_EXCEPTION_CD" VARCHAR2(3), 
	"SERV_EXCEPTION_TX" VARCHAR2(250), 
	"CONSOLIDATED_FLAG" VARCHAR2(1), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_CVS_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_CVS_AUDIT" 
   (	"AUTHORISATION_ID" VARCHAR2(29), 
	"ENTITY" VARCHAR2(4), 
	"INT_MTI" VARCHAR2(4), 
	"SERV_LOG_TS" TIMESTAMP (6), 
	"PMI_ID" VARCHAR2(50), 
	"AVS_VERIFICATION_IND" VARCHAR2(4), 
	"AVS_POST_CODE" VARCHAR2(9), 
	"AVS_ADDRESS_CODE" VARCHAR2(20), 
	"VAL_AVS" VARCHAR2(1), 
	"EXPIRY_DATE" NUMBER(6,0), 
	"BLOCK_CODE" VARCHAR2(2), 
	"FIRST_USAGE_IND" VARCHAR2(1), 
	"STATUS_CODE" VARCHAR2(2), 
	"CANCELLATION_DATE" VARCHAR2(10), 
	"CVS_TRANSACTION_STATUS" VARCHAR2(1), 
	"CONSOLIDATED_FLAG" VARCHAR2(1), 
	"CVS_RESP_CODE" VARCHAR2(3), 
	"FAMILY_ID" VARCHAR2(20), 
	"BRAND_CODE" VARCHAR2(2), 
	"TYPE_CODE" VARCHAR2(2), 
	"CARDHOLDER_ID" VARCHAR2(20), 
	"PRODUCT_ID" VARCHAR2(20), 
	"SUBPRODUCT_ID" VARCHAR2(10), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_DESTINATION_SAF
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_DESTINATION_SAF" 
   (	"ENTITY_ID" VARCHAR2(4), 
	"SAF_ID" VARCHAR2(30) DEFAULT ' ', 
	"AUTHORISATION_ID" VARCHAR2(29) DEFAULT ' ', 
	"DESTINATION_SCHEME_ID" VARCHAR2(3), 
	"OFFLINE_SERVICE_ID" VARCHAR2(3), 
	"CHANNEL_OFFLINE" VARCHAR2(8), 
	"SERV_LOG_TS" TIMESTAMP (6), 
	"SAF_PRIORITY_IN" VARCHAR2(1), 
	"TRN_SYS_ENT_TS" TIMESTAMP (6), 
	"SAF_STATUS" VARCHAR2(1), 
	"SAF_PROCESSED_TS" TIMESTAMP (6), 
	"SAF_ESTIMATED_SEND_TS" TIMESTAMP (6), 
	"SAF_RETRY_NUM" NUMBER(3,0), 
	"SAF_INT_MSG_TX" VARCHAR2(4000), 
	"SAF_INT_MSG_TX_2" VARCHAR2(4000), 
	"PMI_ID" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_DRAWNDOWN_CONTROL
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_DRAWNDOWN_CONTROL" 
   (	"AUTHORISATION_ID" VARCHAR2(29), 
	"BILLING_AMOUNT" NUMBER(15,2), 
	"BILLING_CURRENCY" VARCHAR2(3), 
	"MSG_TYPE_IND" VARCHAR2(1), 
	"LOG_TS" TIMESTAMP (6)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_FVS_LOG
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_FVS_LOG" 
   (	"MSG_KEY" VARCHAR2(36), 
	"MSG_TYPE" VARCHAR2(6), 
	"PMI_ID" VARCHAR2(19), 
	"LOG_TIMESTAMP" TIMESTAMP (6), 
	"PROCESSING_STATUS" VARCHAR2(1), 
	"FRAUD_SCORE" NUMBER(3,0), 
	"MSG_DATA" VARCHAR2(4000), 
	"MSG_DATA_2" VARCHAR2(4000), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_IMS_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_IMS_AUDIT" 
   (	"TRACE_ID" VARCHAR2(50), 
	"TRACE_TS" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ACTION" VARCHAR2(100), 
	"PMI_ID" VARCHAR2(50), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50), 
	"EXCEPTION_ID" VARCHAR2(6), 
	"MESSAGE_DESCRIPTION" VARCHAR2(200), 
	"ADDITIONAL_DATA" VARCHAR2(100), 
	"END_TS" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"START_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"JSON_REQUEST" VARCHAR2(4000), 
	"JSON_RESPONSE" VARCHAR2(4000)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_INSTRUMENT_HOT_CARD
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_INSTRUMENT_HOT_CARD" 
   (	"PMI_ID" VARCHAR2(50), 
	"WHEN_ADDED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ENTITY" VARCHAR2(4)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_LIMIT_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_LIMIT_AUDIT" 
   (	"AUTHORISATION_ID" VARCHAR2(29) DEFAULT ' ', 
	"ACTION_CODE" VARCHAR2(1) DEFAULT ' ', 
	"ENTITY_ID" VARCHAR2(4) DEFAULT ' ', 
	"FAMILY_ID" VARCHAR2(20) DEFAULT ' ', 
	"CARDHOLDER_ID" VARCHAR2(20) DEFAULT ' ', 
	"LIMIT_CURRENCY" VARCHAR2(3) DEFAULT ' ', 
	"ACCUMULATED_LIMIT_TX" VARCHAR2(4000), 
	"SERV_LOG_TS" TIMESTAMP (6) DEFAULT current_timestamp, 
	"APPLIED_LIMIT_PROFILE" VARCHAR2(19), 
	"APPLIED_LIMIT_RULE_CODE" VARCHAR2(4), 
	"LIMIT_RESPONSE_CODE" VARCHAR2(3), 
	"REV_AUTHORISATION_ID" VARCHAR2(29), 
	"FUNCTION_CODE" VARCHAR2(1), 
	"VALIDATION_TYPE" VARCHAR2(1) DEFAULT '1', 
	"PRODUCT_ID" VARCHAR2(20), 
	"SUPRODUCT_ID" VARCHAR2(10), 
	"PMI_BRAND_CODE" VARCHAR2(2), 
	"PMI_TYPE_CODE" VARCHAR2(2), 
	"ACQ_COUNTRY_CODE" NUMBER(9,0), 
	"INT_POS_ENTRY_MODE" VARCHAR2(13), 
	"MCC" VARCHAR2(4), 
	"TRANSACTION_TYPE" VARCHAR2(3), 
	"TRANSACTION_CODE" VARCHAR2(4), 
	"TRANS_CURRENCY_CODE" VARCHAR2(3), 
	"ENTITY_PROFILE" VARCHAR2(19), 
	"PROD_SPROD_PROFILE" VARCHAR2(19), 
	"FAM_CARDHD_PROFILE" VARCHAR2(19), 
	"RULES_VAL_LST_TX" VARCHAR2(4000), 
	"RULES_CRI_LST_TX" VARCHAR2(2000), 
	"TRN_AMOUNT" NUMBER(15,2), 
	"OPERATION_STATUS" VARCHAR2(1), 
	"CUSTOM_CARD_PROFILE_ID" VARCHAR2(19)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_LIMITS_RULE_ACCUMULATES
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_LIMITS_RULE_ACCUMULATES" 
   (	"ENTITY_ID" VARCHAR2(4), 
	"FAMILY_ID" VARCHAR2(20), 
	"CARDHOLDER_ID" VARCHAR2(20), 
	"PROFILE_ID" VARCHAR2(19), 
	"LIMIT_CURRENCY" VARCHAR2(3), 
	"RULE_CODE" VARCHAR2(4), 
	"LIMIT_PERIOD" NUMBER(22,0), 
	"TRANSACTION_NUM_COUNTER" NUMBER(22,127), 
	"ACCUMULATED_AMOUNT" NUMBER(22,127), 
	"FIRST_TRANSACTION_PERIOD_TS" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"LAST_UPDATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) ;
--------------------------------------------------------
--  DDL for Table CK_MBH_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_MBH_AUDIT" 
   (	"AUTHORISATION_ID" VARCHAR2(29), 
	"SCHM_TXN_EXECUTION_SEC_NU" NUMBER(6,0) DEFAULT 0, 
	"SCHEME_ID" VARCHAR2(3), 
	"PMI_ID" VARCHAR2(50), 
	"SCHM_MSG_CODE" VARCHAR2(8), 
	"SCHM_TRANS_DATETIME" VARCHAR2(10), 
	"SCHM_STAN_NU" NUMBER(6,0), 
	"SCHM_FWD_ID" VARCHAR2(11), 
	"SCHM_RESPONSE_CD" VARCHAR2(8), 
	"ACMS_RESPONSE_CD" VARCHAR2(3), 
	"ACMS_TRN_CD" VARCHAR2(3), 
	"RTS_ADQ" VARCHAR2(30), 
	"MSJ_INITIATOR" VARCHAR2(10), 
	"SCHM_TRANSACTION_STATUS" VARCHAR2(1), 
	"CHANNEL_ID" VARCHAR2(8), 
	"PHISICAL_CHANNEL_ID" VARCHAR2(8), 
	"SCHM_START_DATE" TIMESTAMP (6), 
	"SCHM_END_DATE" TIMESTAMP (6), 
	"FILE_UPD_ACTION_CD" VARCHAR2(2), 
	"FILE_UPD_ENTRY_RSN" VARCHAR2(1), 
	"MSJ_ADITIONAL_DATA" VARCHAR2(100), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_MET_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_MET_AUDIT" 
   (	"AUTHORISATION_ID" VARCHAR2(29), 
	"PMI_ID" VARCHAR2(50), 
	"INT_MTI" VARCHAR2(8), 
	"MSG_DATA" VARCHAR2(4000), 
	"SEND_STATUS_IND" VARCHAR2(1), 
	"REQUEST_TS" TIMESTAMP (6), 
	"RESPONSE_TS" TIMESTAMP (6), 
	"SERV_EXCEPTION_CD" VARCHAR2(3), 
	"SERV_EXCEPTION_TX" VARCHAR2(250), 
	"BUSINESS_EXCEPTION_TX" VARCHAR2(250), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_MMH_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" 
   (	"AUTHORISATION_ID" VARCHAR2(29), 
	"SCHEME_ID" VARCHAR2(3), 
	"PMI_ID" VARCHAR2(50), 
	"SERV_LOG_TS" TIMESTAMP (6), 
	"SCHM_MSG_CODE" VARCHAR2(8), 
	"SCHM_PROCESS_CD" VARCHAR2(8), 
	"ACMS_TRN_CD" VARCHAR2(3), 
	"SCHM_TRANS_DATETIME" VARCHAR2(10), 
	"SCHM_STAN_NU" NUMBER(*,0), 
	"SCHM_ACQ_ID" VARCHAR2(11), 
	"SCHM_RESPONSE_CD" VARCHAR2(8), 
	"ACMS_RESPONSE_CD" VARCHAR2(3), 
	"SCHM_DATA_ENTRY_MODE" VARCHAR2(40), 
	"NETWORK_ID" VARCHAR2(4), 
	"SCHM_SESSION_ID" VARCHAR2(11), 
	"ORIGINAL_AUTH_ID" VARCHAR2(29), 
	"SCHM_SETTL_AMOUNT" NUMBER(15,2), 
	"SCHM_SETTL_CURRENCY" VARCHAR2(3), 
	"SCHM_LOCAL_AMOUNT" NUMBER(15,2), 
	"SCHM_LOCAL_CURRENCY" VARCHAR2(3), 
	"SCHM_BILLING_AMOUNT" NUMBER(15,2), 
	"SCHM_BILLING_CURRENCY" VARCHAR2(3), 
	"ACMS_AUTH_AMOUNT" NUMBER(15,2), 
	"SCHM_INCOM_MATCHING_KEY" VARCHAR2(100), 
	"SCHM_AUTH_CODE" VARCHAR2(6), 
	"TERMINAL_ID" VARCHAR2(16), 
	"COMMERCE_ID" VARCHAR2(20), 
	"MSG_DATA" VARCHAR2(4000), 
	"CHANNEL_ID" VARCHAR2(8), 
	"SERV_EXCEPTION_CD" VARCHAR2(3), 
	"SERV_EXCEPTION_TX" VARCHAR2(250), 
	"SCHM_PROCESSED_FLAG" VARCHAR2(1), 
	"SCHM_TRANSACTION_STATUS" VARCHAR2(1), 
	"CONSOLIDATED_FLAG" VARCHAR2(1), 
	"REQUEST_TYPE_FLAG" VARCHAR2(1), 
	"ACMS_DATA_ENTRY_MODE" VARCHAR2(13) DEFAULT NULL, 
	"SCHM_BANKNET_ID" VARCHAR2(100) DEFAULT NULL, 
	"FINANCIAL_FLAG" VARCHAR2(1), 
	"RESOLVER_ID" VARCHAR2(3), 
	"ADV_SCHEME_RESPONSE_CD" VARCHAR2(8), 
	"ADV_SCHEME_REASON_CD" VARCHAR2(7), 
	"AUTH_ADDITIONAL_DATA" VARCHAR2(50), 
	"SCHM_TXN_EXECUTION_SEC_NU" NUMBER(*,0) DEFAULT 0, 
	"SCRIPT_STATUS" VARCHAR2(1), 
	"RPLC_SCHM_LOCAL_AMOUNT" NUMBER(15,2), 
	"RPLC_SCHM_BILLING_AMOUNT" NUMBER(15,2), 
	"ENTITY" VARCHAR2(4) DEFAULT '0224', 
	"FLOW" VARCHAR2(200), 
	"SI_AUTHORISATION_ID" VARCHAR2(29), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_MMH_AUDIT_NET
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT_NET" 
   (	"AUTHORISATION_ID" VARCHAR2(29), 
	"SCHEME_ID" VARCHAR2(3), 
	"SCHM_MSG_CODE" VARCHAR2(8), 
	"SCHM_ACQ_ID" VARCHAR2(11), 
	"SCHM_RESPONSE_CD" VARCHAR2(8), 
	"ACMS_RESPONSE_CD" VARCHAR2(3), 
	"ACMS_TRN_CD" VARCHAR2(3), 
	"RTS_ADQ" VARCHAR2(30), 
	"SCHM_TRANS_DATETIME" VARCHAR2(10), 
	"SCHM_STAN_NU" NUMBER(*,0), 
	"MSJ_INITIATOR" VARCHAR2(10), 
	"SCHM_TRANSACTION_STATUS" VARCHAR2(1), 
	"CHANNEL_ID" VARCHAR2(8), 
	"PHISICAL_CHANNEL_ID" VARCHAR2(8), 
	"SCHM_START_DATE" TIMESTAMP (6), 
	"SCHM_END_DATE" TIMESTAMP (6), 
	"PREVIOUS_STATUS_CONN" VARCHAR2(1), 
	"NEW_STATUS_CONN" VARCHAR2(1), 
	"MSJ_ADITIONAL_DATA" VARCHAR2(200), 
	"ENTITY" VARCHAR2(4) DEFAULT '0224'
   ) ;
--------------------------------------------------------
--  DDL for Table CK_MON_SERVICE_REQUEST
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_MON_SERVICE_REQUEST" 
   (	"SERVICE_ID" VARCHAR2(30), 
	"AUTHORISATION_ID" VARCHAR2(19), 
	"SERV_EXEC_SEC_NU" NUMBER(2,0), 
	"SERV_EXEC_STATUS_TS" TIMESTAMP (6), 
	"SERVICE_POD_ID" VARCHAR2(50), 
	"SERVER_NAME" VARCHAR2(15), 
	"SERV_EXEC_MD" VARCHAR2(1), 
	"SERV_EXEC_STATUS" VARCHAR2(1), 
	"SERV_ORDER_EXEC_NU" VARCHAR2(2), 
	"ENTITY_ID" VARCHAR2(4), 
	"DAY_PART_ID" DATE GENERATED ALWAYS AS (TO_DATE(SUBSTR("AUTHORISATION_ID",1,5),'YYDDD')) VIRTUAL 
   ) ;
--------------------------------------------------------
--  DDL for Table CK_MON_SERVICE_RESPONSE
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_MON_SERVICE_RESPONSE" 
   (	"SERVICE_ID" VARCHAR2(30), 
	"AUTHORISATION_ID" VARCHAR2(19), 
	"SERV_EXEC_SEC_NU" NUMBER(2,0), 
	"SERV_EXEC_STATUS_TS" TIMESTAMP (6), 
	"SERV_EXEC_STATUS" VARCHAR2(1), 
	"SERV_ORDER_EXEC_NU" VARCHAR2(2), 
	"ENTITY_ID" VARCHAR2(4), 
	"DAY_PART_ID" DATE GENERATED ALWAYS AS (TO_DATE(SUBSTR("AUTHORISATION_ID",1,5),'YYDDD')) VIRTUAL 
   ) ;
--------------------------------------------------------
--  DDL for Table CK_MON_TRANSACTION_QUALITY
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_MON_TRANSACTION_QUALITY" 
   (	"SERVICE_ID" VARCHAR2(30), 
	"AUTHORISATION_ID" VARCHAR2(19), 
	"SERV_EXEC_SEC_NU" NUMBER(2,0), 
	"SYS_ENT_TS" TIMESTAMP (6), 
	"ENTITY_ID" VARCHAR2(4), 
	"SCHEME_ID" VARCHAR2(3), 
	"PMI_ID" VARCHAR2(50), 
	"SCHM_MSG_CODE" VARCHAR2(8), 
	"INTERNAL_TRN_CD" VARCHAR2(3), 
	"INT_RESP_CODE" VARCHAR2(3), 
	"AUT_RESULT_IND" VARCHAR2(1), 
	"CHANNEL_ID" VARCHAR2(8), 
	"RESOLVER_ID" VARCHAR2(3), 
	"SCHM_TRN_STATUS" VARCHAR2(1), 
	"ADV_RESPONSE_CD" VARCHAR2(3), 
	"ADV_REASON_CD" VARCHAR2(4), 
	"ADV_DETAIL_CD" VARCHAR2(4), 
	"DAY_PART_ID" DATE GENERATED ALWAYS AS (TO_DATE(SUBSTR("AUTHORISATION_ID",1,5),'YYDDD')) VIRTUAL 
   ) ;
--------------------------------------------------------
--  DDL for Table CK_MQ_RESEND_LOG
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_MQ_RESEND_LOG" 
   (	"EXCHANGE" VARCHAR2(50), 
	"AUTHORISATION_ID" VARCHAR2(29), 
	"SERV_ORDER_EXEC_NU" VARCHAR2(2), 
	"PROCESS_STATUS" VARCHAR2(2), 
	"LAST_UPDATE_TS" TIMESTAMP (6), 
	"RETRIES_NUM" NUMBER(22,127), 
	"SERVICE_ID" VARCHAR2(30), 
	"SERV_DATA_HEADERS" VARCHAR2(2000), 
	"SERV_DATA" VARCHAR2(4000), 
	"SERV_DATA_2" VARCHAR2(4000)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_MSG_LOG
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_MSG_LOG" 
   (	"SCHEME_ID" VARCHAR2(3), 
	"AUTHORISATION_ID" VARCHAR2(29), 
	"MSG_TYPE" VARCHAR2(2), 
	"MSG_MTI" NUMBER(*,0), 
	"LOG_TS" TIMESTAMP (6), 
	"MSG_DATA" VARCHAR2(4000)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_PARAMETER_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_PARAMETER_AUDIT" 
   (	"TABLE_NAME" VARCHAR2(50) DEFAULT ' ', 
	"LOGGING_TS" TIMESTAMP (6) DEFAULT TO_DATE('9999-12-31 23:59:59','YYYY-MM-DDHH24:MI:SS'), 
	"ACTION_CODE" VARCHAR2(1) DEFAULT ' ', 
	"TABLE_KEY_DATA" VARCHAR2(50) DEFAULT ' ', 
	"USER_ID" VARCHAR2(8) DEFAULT ' ', 
	"USER_TERMINAL" VARCHAR2(20), 
	"TABLE_DATA" VARCHAR2(4000)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_PIN_CHANGE_LOG
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_PIN_CHANGE_LOG" 
   (	"AUTHORISATION_ID" VARCHAR2(29) DEFAULT ' ', 
	"PMI_ID" VARCHAR2(50), 
	"PMI_SEC_NU" NUMBER(3,0), 
	"PIN_VAL_TYPE" VARCHAR2(2), 
	"SERV_LOG_TS" TIMESTAMP (6), 
	"PREV_OFFSET" NUMBER(9,0), 
	"PREV_PIN_DATA_OTHER" VARCHAR2(64), 
	"EXPIRY_DATE" NUMBER(8,0), 
	"EST_PIN_IN" VARCHAR2(1), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_SAF_DESTINATION_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_SAF_DESTINATION_SCHEDULE" 
   (	"TASK_ID" VARCHAR2(60) DEFAULT ' ', 
	"TASK_TYPE" VARCHAR2(2) DEFAULT '00', 
	"TASK_STATUS" VARCHAR2(1) DEFAULT 'I', 
	"TASK_LAST_UPDATE_TS" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"TASK_PARAMETERS" VARCHAR2(1000)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_SAF_SENDER_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_SAF_SENDER_SCHEDULE" 
   (	"TASK_ID" VARCHAR2(60) DEFAULT ' ', 
	"TASK_TYPE" VARCHAR2(2) DEFAULT '00', 
	"TASK_STATUS" VARCHAR2(1) DEFAULT 'I', 
	"TASK_LAST_UPDATE_TS" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"TASK_PARAMETERS" VARCHAR2(1000)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_SAF_STATUS
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_SAF_STATUS" 
   (	"ENTITY" VARCHAR2(4), 
	"SAF_ID" VARCHAR2(30), 
	"SAF_PROCESSING_STATUS" VARCHAR2(1), 
	"LAST_STATUS_UPDATE_TS" TIMESTAMP (6), 
	"START_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6), 
	"LAST_UPDATE" TIMESTAMP (6)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_SAT_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_SAT_AUDIT" 
   (	"SCHEME_ID" VARCHAR2(3), 
	"AUTHORISATION_ID" VARCHAR2(29) DEFAULT ' ', 
	"DESTINATION_AUTH_ID" VARCHAR2(19), 
	"PMI_ID" VARCHAR2(50), 
	"SERV_LOG_TS" TIMESTAMP (6), 
	"TRN_TYPE_CD" VARCHAR2(8), 
	"DESTINATION_PROCESS_CD" VARCHAR2(8), 
	"RESPONSE_CD" VARCHAR2(3), 
	"DESTINATION_RESPONSE_CD" VARCHAR2(8), 
	"ORIGINAL_AUTH_ID" VARCHAR2(29), 
	"SCHM_LOCAL_AMOUNT" NUMBER(15,2), 
	"SCHM_LOCAL_CURRENCY" VARCHAR2(3), 
	"BILLING_AMOUNT" NUMBER(15,2), 
	"BILLING_CURRENCY" VARCHAR2(3), 
	"AUTHORISED_AMOUNT" NUMBER(15,2), 
	"TRN_EXCHG_RATE" NUMBER(15,0), 
	"AUTH_CODE" VARCHAR2(6), 
	"TRN_TS" TIMESTAMP (6), 
	"TRN_MCC" VARCHAR2(4), 
	"TERMINAL_ID" VARCHAR2(16), 
	"COMMERCE_ID" VARCHAR2(20), 
	"COMMERCE_NAME" VARCHAR2(50), 
	"TERM_CITY_LOC" VARCHAR2(50), 
	"TERM_COUNTRY_LOC" VARCHAR2(3), 
	"POSTING_ACCOUNT" VARCHAR2(40), 
	"SERV_EXCEPTION_CD" VARCHAR2(3), 
	"SERV_EXCEPTION_TX" VARCHAR2(250), 
	"FUNCT_EXCEPTION_TX" VARCHAR2(250), 
	"REQUEST_TYPE_FLAG" VARCHAR2(1), 
	"TRN_STATUS" VARCHAR2(1), 
	"CONSOLIDATED_FLAG" VARCHAR2(1), 
	"INT_DATA_ENTRY_MODE" VARCHAR2(13), 
	"DEST_POS_ENTRY_MODE" VARCHAR2(40), 
	"PMI_PSN" NUMBER(3,0), 
	"FIRST_USAGE_IND" VARCHAR2(1), 
	"CASHBACK_AMOUNT" NUMBER(15,2), 
	"PARTIAL_AUTH_IND" VARCHAR2(1), 
	"TRANS_TYPE_SIGN" VARCHAR2(1), 
	"FINANC_TRANS_IND" VARCHAR2(1), 
	"DAILY_LIMIT_CTRL_IND" VARCHAR2(1), 
	"EXPIRY_DATE_VAL_IND" VARCHAR2(1), 
	"ADV_RESP_CODE" VARCHAR2(3), 
	"ORIG_INT_MTI" VARCHAR2(4), 
	"AFD_IND" VARCHAR2(1), 
	"INT_MTI" VARCHAR2(4), 
	"LEDGER_BALANCE" NUMBER(15,2), 
	"AVAILABLE_BALANCE" NUMBER(15,2), 
	"INT_RESOLVER_CD" VARCHAR2(3), 
	"POS_COUNTRY_CODE" VARCHAR2(3), 
	"POS_POSTAL_CODE" VARCHAR2(10), 
	"PARTIAL_REVERSAL_IND" VARCHAR2(1), 
	"REPL_AUTHORISATION_ID" VARCHAR2(29), 
	"REPL_LOCAL_AMOUNT" NUMBER(15,2), 
	"REPL_BILLING_AMOUNT" NUMBER(15,2), 
	"REQUEST_TS" TIMESTAMP (6), 
	"RESPONSE_TS" TIMESTAMP (6), 
	"DEST_CHANNEL_ID" VARCHAR2(8), 
	"DEST_MTI" VARCHAR2(4), 
	"SESSION_ID" VARCHAR2(10), 
	"FLOW" VARCHAR2(200), 
	"REV_AUTHORISATION_ID" VARCHAR2(29), 
	"ENTITY" VARCHAR2(4), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_SAT_AUDIT_NET
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_SAT_AUDIT_NET" 
   (	"AUTHORISATION_ID" VARCHAR2(29), 
	"SCHEME_ID" VARCHAR2(3), 
	"SCHM_MSG_CODE" VARCHAR2(8), 
	"SCHM_ACQ_ID" VARCHAR2(11), 
	"SCHM_RESPONSE_CD" VARCHAR2(8), 
	"ACMS_RESPONSE_CD" VARCHAR2(3), 
	"ACMS_TRN_CD" VARCHAR2(3), 
	"RTS_ADQ" VARCHAR2(30), 
	"SCHM_TRANS_DATETIME" VARCHAR2(20), 
	"SCHM_STAN_NU" NUMBER(*,0), 
	"MSJ_INITIATOR" VARCHAR2(10), 
	"SCHM_TRANSACTION_STATUS" VARCHAR2(1), 
	"CHANNEL_ID" VARCHAR2(8), 
	"PHISICAL_CHANNEL_ID" VARCHAR2(8), 
	"SCHM_START_DATE" TIMESTAMP (6), 
	"SCHM_END_DATE" TIMESTAMP (6), 
	"PREVIOUS_STATUS_CONN" VARCHAR2(1), 
	"NEW_STATUS_CONN" VARCHAR2(1), 
	"MSJ_ADITIONAL_DATA" VARCHAR2(200), 
	"ENTITY" VARCHAR2(4) DEFAULT '0014'
   ) ;
--------------------------------------------------------
--  DDL for Table CK_SAT_LOG
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_SAT_LOG" 
   (	"SCHEME_ID" VARCHAR2(3), 
	"AUTHORISATION_ID" VARCHAR2(29) DEFAULT ' ', 
	"DESTINATION_AUTH_ID" VARCHAR2(19), 
	"MSG_TYPE" VARCHAR2(3), 
	"MSG_MTI" VARCHAR2(4), 
	"LOG_TS" TIMESTAMP (6), 
	"MSG_DATA" VARCHAR2(4000), 
	"MSG_FORMAT" VARCHAR2(10)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_SAT_OFFLINE_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_SAT_OFFLINE_AUDIT" 
   (	"SCHEME_ID" VARCHAR2(3), 
	"AUTHORISATION_ID" VARCHAR2(29) DEFAULT ' ', 
	"DESTINATION_AUTH_ID" VARCHAR2(19), 
	"PMI_ID" VARCHAR2(50), 
	"SERV_LOG_TS" TIMESTAMP (6), 
	"TRN_TYPE_CD" VARCHAR2(8), 
	"DESTINATION_PROCESS_CD" VARCHAR2(8), 
	"RESPONSE_CD" VARCHAR2(3), 
	"DESTINATION_RESPONSE_CD" VARCHAR2(8), 
	"ORIGINAL_AUTH_ID" VARCHAR2(29), 
	"SCHM_LOCAL_AMOUNT" NUMBER(15,2), 
	"SCHM_LOCAL_CURRENCY" VARCHAR2(3), 
	"BILLING_AMOUNT" NUMBER(15,2), 
	"BILLING_CURRENCY" VARCHAR2(3), 
	"AUTHORISED_AMOUNT" NUMBER(15,2), 
	"TRN_EXCHG_RATE" NUMBER(15,0), 
	"AUTH_CODE" VARCHAR2(6), 
	"TRN_TS" TIMESTAMP (6), 
	"TRN_MCC" VARCHAR2(4), 
	"TERMINAL_ID" VARCHAR2(16), 
	"COMMERCE_ID" VARCHAR2(20), 
	"COMMERCE_NAME" VARCHAR2(50), 
	"TERM_CITY_LOC" VARCHAR2(50), 
	"TERM_COUNTRY_LOC" VARCHAR2(3), 
	"POSTING_ACCOUNT" VARCHAR2(40), 
	"SERV_EXCEPTION_CD" VARCHAR2(3), 
	"SERV_EXCEPTION_TX" VARCHAR2(250), 
	"FUNCT_EXCEPTION_TX" VARCHAR2(250), 
	"REQUEST_TYPE_FLAG" VARCHAR2(1), 
	"TRN_STATUS" VARCHAR2(1), 
	"CONSOLIDATED_FLAG" VARCHAR2(1), 
	"INT_DATA_ENTRY_MODE" VARCHAR2(13), 
	"DEST_POS_ENTRY_MODE" VARCHAR2(40), 
	"PMI_PSN" NUMBER(3,0), 
	"FIRST_USAGE_IND" VARCHAR2(1), 
	"CASHBACK_AMOUNT" NUMBER(15,2), 
	"PARTIAL_AUTH_IND" VARCHAR2(1), 
	"TRANS_TYPE_SIGN" VARCHAR2(1), 
	"FINANC_TRANS_IND" VARCHAR2(1), 
	"DAILY_LIMIT_CTRL_IND" VARCHAR2(1), 
	"EXPIRY_DATE_VAL_IND" VARCHAR2(1), 
	"ADV_RESP_CODE" VARCHAR2(3), 
	"ORIG_INT_MTI" VARCHAR2(4), 
	"AFD_IND" VARCHAR2(1), 
	"INT_MTI" VARCHAR2(4), 
	"LEDGER_BALANCE" NUMBER(15,2), 
	"AVAILABLE_BALANCE" NUMBER(15,2), 
	"STRATOS_INT_RESOLVER" VARCHAR2(3), 
	"POS_COUNTRY_CODE" VARCHAR2(3), 
	"POS_POSTAL_CODE" VARCHAR2(10), 
	"PARTIAL_REVERSAL_IND" VARCHAR2(1), 
	"REPL_AUTHORISATION_ID" VARCHAR2(29), 
	"REPL_LOCAL_AMOUNT" NUMBER(15,2), 
	"REPL_BILLING_AMOUNT" NUMBER(15,2), 
	"REQUEST_TS" TIMESTAMP (6), 
	"RESPONSE_TS" TIMESTAMP (6), 
	"DEST_CHANNEL_ID" VARCHAR2(8), 
	"DEST_MTI" VARCHAR2(4), 
	"SESSION_ID" VARCHAR2(10), 
	"FLOW" VARCHAR2(200), 
	"ENTITY" VARCHAR2(4), 
	"RETRY_IND" VARCHAR2(1), 
	"REV_AUTHORISATION_ID" VARCHAR2(29), 
	"FAKE_TRN_IND" VARCHAR2(1), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_STIP_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_STIP_AUDIT" 
   (	"ENTITY" VARCHAR2(4), 
	"SCHEME_ID" VARCHAR2(3), 
	"AUTHORISATION_ID" VARCHAR2(29) DEFAULT ' ', 
	"SI_AUTHORISATION_ID" VARCHAR2(29), 
	"PMI_ID" VARCHAR2(50), 
	"INT_MTI" VARCHAR2(4), 
	"SERV_LOG_TS" TIMESTAMP (6), 
	"TRN_TYPE_CD" VARCHAR2(8), 
	"BILLING_AMOUNT" NUMBER(15,2), 
	"BILLING_CURRENCY" VARCHAR2(3), 
	"TRN_AMOUNT" NUMBER(15,2), 
	"TRN_CURRENCY" VARCHAR2(3), 
	"TRN_EXCHG_RATE" NUMBER(15,0), 
	"TRN_TIMESTAMP" TIMESTAMP (6), 
	"TRN_STATUS" VARCHAR2(1), 
	"AUTHORISED_AMOUNT" NUMBER(15,2), 
	"AUTH_CODE" VARCHAR2(6), 
	"RESPONSE_CD" VARCHAR2(3), 
	"DEST_INT_RESOLVER" VARCHAR2(3), 
	"LIMIT_RESPCODE" VARCHAR2(3), 
	"APPLIED_LIMIT_PROFILE" VARCHAR2(19), 
	"FVS_INT_RESPCODE" VARCHAR2(3), 
	"BALANCE_RESPCODE" VARCHAR2(3), 
	"LIMIT_VAL_SEND_STATUS" VARCHAR2(1), 
	"BALANCE_SEND_STATUS" VARCHAR2(1), 
	"FVS_SEND_STATUS" VARCHAR2(1), 
	"TRN_MCC" VARCHAR2(4), 
	"ACQ_COUNTRY_CODE" VARCHAR2(3), 
	"INT_DATA_ENTRY_MODE" VARCHAR2(13), 
	"DBCR_INDICATOR" VARCHAR2(1), 
	"POSTING_ACCOUNT" VARCHAR2(40), 
	"STIP_MODE" VARCHAR2(1), 
	"TRANSACTION_TYPE_SIGN" VARCHAR2(1), 
	"FINANCIAL_FLAG" VARCHAR2(1), 
	"STIP_ALLOWED" VARCHAR2(1), 
	"FRAUD_SEND_IND" VARCHAR2(1), 
	"SERV_EXCEPTION_CD" VARCHAR2(3), 
	"SERV_EXCEPTION_TX" VARCHAR2(250), 
	"FUNCT_EXCEPTION_TX" VARCHAR2(250), 
	"FLOW" VARCHAR2(200), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_TASK_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_TASK_SCHEDULE" 
   (	"TASK_ID" VARCHAR2(40) DEFAULT ' ', 
	"TASK_TYPE" VARCHAR2(2) DEFAULT '00', 
	"TASK_STATUS" VARCHAR2(1) DEFAULT 'I', 
	"TASK_LAST_UPDATE_TS" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"TASK_MESSAGE" VARCHAR2(1000)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_TDD_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_TDD_AUDIT" 
   (	"AUTHORISATION_ID" VARCHAR2(29), 
	"PMI_ID" VARCHAR2(50), 
	"SERV_LOG_TS" TIMESTAMP (6), 
	"SERVICES_DISPATCH_INFO" VARCHAR2(4000), 
	"STATUS" VARCHAR2(1), 
	"SERV_EXCEPTION_CD" VARCHAR2(3), 
	"SERV_EXCEPTION_TX" VARCHAR2(250), 
	"BUSINESS_EXCEPTION_TX" VARCHAR2(250), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_TIME_OUT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_TIME_OUT" 
   (	"TIMEOUT_ID" VARCHAR2(100), 
	"ACTION" VARCHAR2(4000)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_TRANSACTION_COUNTERS
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_TRANSACTION_COUNTERS" 
   (	"ENTITY" VARCHAR2(4), 
	"PMI_ID" VARCHAR2(50), 
	"PMI_SEC_NU" NUMBER(*,0), 
	"ATC" NUMBER(*,0), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"FALLBACK_TRANS_NUM_COUNTER" NUMBER(12,0), 
	"FALLBACK_ACCUMULATED_AMOUNT" NUMBER(15,2)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_USER_TOKEN
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_USER_TOKEN" 
   (	"ENTITY" VARCHAR2(4), 
	"USER_ID" VARCHAR2(8), 
	"USER_SESION_NUMBER" NUMBER(8,0), 
	"USER_PROFILE_ID" NUMBER(3,0), 
	"USER_SESION_TOKEN" VARCHAR2(4000), 
	"USER_SESION_PROFILE" VARCHAR2(4000), 
	"USER_SESION_PROFILE_2" VARCHAR2(4000), 
	"START_DATE" TIMESTAMP (6) DEFAULT current_timestamp, 
	"END_DATE" TIMESTAMP (6) DEFAULT TO_DATE('9999-12-31 23:59:59','YYYY-MM-DDHH24:MI:SS'), 
	"LAST_UPDATE" TIMESTAMP (6) DEFAULT current_timestamp
   ) ;
--------------------------------------------------------
--  DDL for Table CK_VMH_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" 
   (	"AUTHORISATION_ID" VARCHAR2(29), 
	"SCHEME_ID" VARCHAR2(3), 
	"PMI_ID" VARCHAR2(50), 
	"SERV_LOG_TS" TIMESTAMP (6), 
	"SCHM_MSG_CODE" VARCHAR2(8), 
	"SCHM_PROCESS_CD" VARCHAR2(8), 
	"ACMS_TRN_CD" VARCHAR2(3), 
	"SCHM_TRANS_DATETIME" VARCHAR2(10), 
	"SCHM_STAN_NU" NUMBER(22,0), 
	"SCHM_ACQ_ID" VARCHAR2(11), 
	"SCHM_RESPONSE_CD" VARCHAR2(8), 
	"ACMS_RESPONSE_CD" VARCHAR2(3), 
	"SCHM_DATA_ENTRY_MODE" VARCHAR2(40), 
	"NETWORK_ID" VARCHAR2(4), 
	"ORIGINAL_AUTH_ID" VARCHAR2(29), 
	"SCHM_SETTL_AMOUNT" NUMBER(15,2), 
	"SCHM_SETTL_CURRENCY" VARCHAR2(3), 
	"SCHM_LOCAL_AMOUNT" NUMBER(15,2), 
	"SCHM_LOCAL_CURRENCY" VARCHAR2(3), 
	"SCHM_BILLING_AMOUNT" NUMBER(15,2), 
	"SCHM_BILLING_CURRENCY" VARCHAR2(3), 
	"ACMS_AUTH_AMOUNT" NUMBER(15,2), 
	"SCHM_INCOM_MATCHING_KEY" VARCHAR2(100), 
	"SCHM_AUTH_CODE" VARCHAR2(6), 
	"TERMINAL_ID" VARCHAR2(16), 
	"COMMERCE_ID" VARCHAR2(20), 
	"MCC" VARCHAR2(4), 
	"TRANSACTION_CODE" VARCHAR2(4), 
	"COUNTRY_CODE" VARCHAR2(3), 
	"AVS_VAL_RES" VARCHAR2(1), 
	"MSG_DATA" VARCHAR2(4000), 
	"CHANNEL_ID" VARCHAR2(8), 
	"SERV_EXCEPTION_CD" VARCHAR2(3), 
	"SERV_EXCEPTION_TX" VARCHAR2(250), 
	"SCHM_PROCESSED_FLAG" VARCHAR2(1), 
	"SCHM_TRANSACTION_STATUS" VARCHAR2(1), 
	"CONSOLIDATED_FLAG" VARCHAR2(1), 
	"REQUEST_TYPE_FLAG" VARCHAR2(1), 
	"ACMS_DATA_ENTRY_MODE" VARCHAR2(13) DEFAULT NULL, 
	"FINANCIAL_FLAG" VARCHAR2(1), 
	"RESOLVER_ID" VARCHAR2(3), 
	"ADV_SCHEME_RESPONSE_CD" VARCHAR2(8), 
	"ADV_SCHEME_REASON_CD" VARCHAR2(7), 
	"AUTH_ADDITIONAL_DATA" VARCHAR2(50), 
	"SCHM_TXN_EXECUTION_SEC_NU" NUMBER(22,0) DEFAULT 0, 
	"SCRIPT_STATUS" VARCHAR2(1), 
	"RPLC_SCHM_LOCAL_AMOUNT" NUMBER(15,2), 
	"RPLC_SCHM_BILLING_AMOUNT" NUMBER(15,2), 
	"ENTITY" VARCHAR2(4) DEFAULT '0224', 
	"SCHM_RETRIEVAL_REF_NUM" VARCHAR2(12), 
	"FLOW" VARCHAR2(200), 
	"SI_AUTHORISATION_ID" VARCHAR2(29), 
	"PAYMENT_INSTRUMENT_NUMBER" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_VMH_AUDIT_NET
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT_NET" 
   (	"AUTHORISATION_ID" VARCHAR2(29), 
	"SCHEME_ID" VARCHAR2(3), 
	"SCHM_MSG_CODE" VARCHAR2(8), 
	"SCHM_ACQ_ID" VARCHAR2(11), 
	"SCHM_RESPONSE_CD" VARCHAR2(8), 
	"ACMS_RESPONSE_CD" VARCHAR2(3), 
	"ACMS_TRN_CD" VARCHAR2(3), 
	"RTS_ADQ" VARCHAR2(30), 
	"SCHM_TRANS_DATETIME" VARCHAR2(10), 
	"SCHM_STAN_NU" NUMBER(*,0), 
	"MSJ_INITIATOR" VARCHAR2(10), 
	"SCHM_TRANSACTION_STATUS" VARCHAR2(1), 
	"CHANNEL_ID" VARCHAR2(8), 
	"PHISICAL_CHANNEL_ID" VARCHAR2(8), 
	"SCHM_START_DATE" TIMESTAMP (6), 
	"SCHM_END_DATE" TIMESTAMP (6), 
	"PREVIOUS_STATUS_CONN" VARCHAR2(1), 
	"NEW_STATUS_CONN" VARCHAR2(1), 
	"MSJ_ADITIONAL_DATA" VARCHAR2(200), 
	"ENTITY" VARCHAR2(4) DEFAULT '0224'
   ) ;
--------------------------------------------------------
--  DDL for Table CK_WFT_AUDIT
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_WFT_AUDIT" 
   (	"SERVICE_ID" VARCHAR2(30), 
	"AUTHORISATION_ID" VARCHAR2(19), 
	"SERV_EXEC_SEC_NU" NUMBER(2,0), 
	"SERV_EXEC_STATUS_TS" TIMESTAMP (6), 
	"SERVICE_POD_ID" VARCHAR2(50), 
	"SERVER_NAME" VARCHAR2(15), 
	"SERV_EXEC_MD" VARCHAR2(1), 
	"SERV_EXEC_STATUS" VARCHAR2(1), 
	"SERV_ORDER_EXEC_NU" VARCHAR2(2), 
	"TRANSACTION_STATUS" VARCHAR2(1), 
	"INT_RESP_CODE" VARCHAR2(3), 
	"SERV_DATA_HEADER" VARCHAR2(2000), 
	"SERV_EXCEPTION_CD" VARCHAR2(6), 
	"CONSOLIDATED_FLAG" VARCHAR2(1), 
	"SERV_DATA" VARCHAR2(4000), 
	"SERV_DATA_2" VARCHAR2(4000)
   ) ;
--------------------------------------------------------
--  DDL for Table CK_WFT_RESEND_LOG
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."CK_WFT_RESEND_LOG" 
   (	"SERVICE_ID" VARCHAR2(30) DEFAULT ' ', 
	"AUTHORISATION_ID" VARCHAR2(29) DEFAULT ' ', 
	"SERV_ORDER_EXEC_NU" VARCHAR2(2) DEFAULT ' ', 
	"PROCESS_STATUS" VARCHAR2(10), 
	"LAST_UPDATE_TS" TIMESTAMP (6), 
	"RETRIES_NUM" NUMBER(3,0), 
	"WFT_SERV_DATA" CLOB
   ) ;
--------------------------------------------------------
--  DDL for Table DATABASECHANGELOG
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."DATABASECHANGELOG" 
   (	"ID" VARCHAR2(255), 
	"AUTHOR" VARCHAR2(255), 
	"FILENAME" VARCHAR2(255), 
	"DATEEXECUTED" TIMESTAMP (6), 
	"ORDEREXECUTED" NUMBER(*,0), 
	"EXECTYPE" VARCHAR2(10), 
	"MD5SUM" VARCHAR2(35), 
	"DESCRIPTION" VARCHAR2(255), 
	"COMMENTS" VARCHAR2(255), 
	"TAG" VARCHAR2(255), 
	"LIQUIBASE" VARCHAR2(20), 
	"CONTEXTS" VARCHAR2(255), 
	"LABELS" VARCHAR2(255), 
	"DEPLOYMENT_ID" VARCHAR2(10)
   ) ;
--------------------------------------------------------
--  DDL for Table DATABASECHANGELOGLOCK
--------------------------------------------------------

  CREATE TABLE "STRATOS_MX_TRANS"."DATABASECHANGELOGLOCK" 
   (	"ID" NUMBER(*,0), 
	"LOCKED" NUMBER(1,0), 
	"LOCKGRANTED" TIMESTAMP (6), 
	"LOCKEDBY" VARCHAR2(255)
   ) ;
--------------------------------------------------------
--  DDL for Index CK_BALANCES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."CK_BALANCES_PK" ON "STRATOS_MX_TRANS"."CK_BALANCES" ("ENTITY", "ACCOUNT_ID") 
  ;
--------------------------------------------------------
--  DDL for Index CK_LIMIT_AUDIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."CK_LIMIT_AUDIT_PK" ON "STRATOS_MX_TRANS"."CK_LIMIT_AUDIT" ("AUTHORISATION_ID", "ACTION_CODE", "VALIDATION_TYPE") 
  ;
--------------------------------------------------------
--  DDL for Index CK_PARAMETER_AUDIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."CK_PARAMETER_AUDIT_PK" ON "STRATOS_MX_TRANS"."CK_PARAMETER_AUDIT" ("TABLE_NAME", "LOGGING_TS", "ACTION_CODE", "TABLE_KEY_DATA", "USER_ID") 
  ;
--------------------------------------------------------
--  DDL for Index CK_PIN_CHANGE_LOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."CK_PIN_CHANGE_LOG_PK" ON "STRATOS_MX_TRANS"."CK_PIN_CHANGE_LOG" ("AUTHORISATION_ID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_DATABASECHANGELOGLOCK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."PK_DATABASECHANGELOGLOCK" ON "STRATOS_MX_TRANS"."DATABASECHANGELOGLOCK" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C0011181
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."SYS_C0011181" ON "STRATOS_MX_TRANS"."CK_TDD_AUDIT" ("AUTHORISATION_ID") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C0011551
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."SYS_C0011551" ON "STRATOS_MX_TRANS"."CK_MET_AUDIT" ("AUTHORISATION_ID") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C0011693
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."SYS_C0011693" ON "STRATOS_MX_TRANS"."CK_SAF_DESTINATION_SCHEDULE" ("TASK_ID") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C0011912
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."SYS_C0011912" ON "STRATOS_MX_TRANS"."CK_AMH_AUDIT" ("AUTHORISATION_ID") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C0012000
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."SYS_C0012000" ON "STRATOS_MX_TRANS"."CK_AMH_AUDIT_NET" ("AUTHORISATION_ID") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C0012218
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."SYS_C0012218" ON "STRATOS_MX_TRANS"."CK_STIP_AUDIT" ("AUTHORISATION_ID") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C0012219
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."SYS_C0012219" ON "STRATOS_MX_TRANS"."CK_DRAWNDOWN_CONTROL" ("AUTHORISATION_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_AMH_AUDIT_UI_4
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_AMH_AUDIT_UI_4" ON "STRATOS_MX_TRANS"."CK_AMH_AUDIT" ("COMMERCE_ID", "PMI_ID", "SCHM_MSG_CODE", "SCHM_LOCAL_AMOUNT", "SCHM_LOCAL_CURRENCY") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_AMH_AUDIT_UI1
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_AMH_AUDIT_UI1" ON "STRATOS_MX_TRANS"."CK_AMH_AUDIT" ("SCHM_MSG_CODE", "SCHM_STAN_NU", "SCHM_TRANS_DATETIME", "SCHM_ACQ_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_WFT_RESEND_LOG_1
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_WFT_RESEND_LOG_1" ON "STRATOS_MX_TRANS"."CK_WFT_RESEND_LOG" ("SERVICE_ID", "PROCESS_STATUS", "LAST_UPDATE_TS") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_AMH_AUDIT_UI2
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_AMH_AUDIT_UI2" ON "STRATOS_MX_TRANS"."CK_AMH_AUDIT" ("PMI_ID", "SCHM_STAN_NU", "SCHM_TRANS_DATETIME", "SCHM_MSG_CODE") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_AMH_AUDIT_UI_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."IDX_CK_AMH_AUDIT_UI_1" ON "STRATOS_MX_TRANS"."CK_AMH_AUDIT" ("SCHM_MSG_CODE", "SCHM_STAN_NU", "SCHM_ACQ_ID", "SCHM_TXN_EXECUTION_SEC_NU", "SCHM_TRANS_DATETIME") 
  ;
--------------------------------------------------------
--  DDL for Index CK_PIN_CHANGE_LOG_IDX1
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."CK_PIN_CHANGE_LOG_IDX1" ON "STRATOS_MX_TRANS"."CK_PIN_CHANGE_LOG" ("PMI_ID", "PMI_SEC_NU") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_MMH_AUDIT_KEY2
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_MMH_AUDIT_KEY2" ON "STRATOS_MX_TRANS"."CK_MMH_AUDIT" ("PMI_ID", "SCHM_LOCAL_AMOUNT", "SCHM_LOCAL_CURRENCY", "SCHM_BANKNET_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_VMH_AUDIT_UI_2
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_VMH_AUDIT_UI_2" ON "STRATOS_MX_TRANS"."CK_VMH_AUDIT" ("PMI_ID", "SCHM_STAN_NU", "SCHM_MSG_CODE") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_AMH_AUDIT_KEY2
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_AMH_AUDIT_KEY2" ON "STRATOS_MX_TRANS"."CK_AMH_AUDIT" ("PMI_ID", "SCHM_LOCAL_AMOUNT", "SCHM_LOCAL_CURRENCY") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_MMH_AUDIT_NET_UI1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."IDX_CK_MMH_AUDIT_NET_UI1" ON "STRATOS_MX_TRANS"."CK_MMH_AUDIT_NET" ("RTS_ADQ") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_MMH_AUDIT_UI3
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_MMH_AUDIT_UI3" ON "STRATOS_MX_TRANS"."CK_MMH_AUDIT" ("SCHM_INCOM_MATCHING_KEY", "SCHM_AUTH_CODE") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_SAT_AUDIT_UI1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."IDX_CK_SAT_AUDIT_UI1" ON "STRATOS_MX_TRANS"."CK_SAT_AUDIT" ("DESTINATION_AUTH_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_AMH_AUDIT_UI3
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_AMH_AUDIT_UI3" ON "STRATOS_MX_TRANS"."CK_AMH_AUDIT" ("SCHM_INCOM_MATCHING_KEY", "SCHM_AUTH_CODE") 
  ;
--------------------------------------------------------
--  DDL for Index INDX2
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."INDX2" ON "STRATOS_MX_TRANS"."CK_MON_SERVICE_REQUEST" ("AUTHORISATION_ID", "SERV_EXEC_STATUS_TS", "SERVICE_ID", "DAY_PART_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_FVS_LOG_UI2
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_FVS_LOG_UI2" ON "STRATOS_MX_TRANS"."CK_FVS_LOG" ("PROCESSING_STATUS") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_VMH_AUDIT_UI3
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_VMH_AUDIT_UI3" ON "STRATOS_MX_TRANS"."CK_VMH_AUDIT" ("SCHM_INCOM_MATCHING_KEY", "SCHM_AUTH_CODE") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_MBH_AUDIT_K1_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."IDX_CK_MBH_AUDIT_K1_2" ON "STRATOS_MX_TRANS"."CK_MBH_AUDIT" ("RTS_ADQ") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_FVS_LOG_UI1
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_FVS_LOG_UI1" ON "STRATOS_MX_TRANS"."CK_FVS_LOG" ("PMI_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_AMH_AUDIT_UI_2
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_AMH_AUDIT_UI_2" ON "STRATOS_MX_TRANS"."CK_AMH_AUDIT" ("PMI_ID", "SCHM_STAN_NU", "SCHM_MSG_CODE") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_VMH_AUDIT_UI_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."IDX_CK_VMH_AUDIT_UI_1" ON "STRATOS_MX_TRANS"."CK_VMH_AUDIT" ("SCHM_MSG_CODE", "SCHM_STAN_NU", "SCHM_ACQ_ID", "SCHM_TXN_EXECUTION_SEC_NU", "SCHM_TRANS_DATETIME") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_VMH_AUDIT_UI2
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_VMH_AUDIT_UI2" ON "STRATOS_MX_TRANS"."CK_VMH_AUDIT" ("PMI_ID", "SCHM_STAN_NU", "SCHM_TRANS_DATETIME", "SCHM_MSG_CODE") 
  ;
--------------------------------------------------------
--  DDL for Index INDX1
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."INDX1" ON "STRATOS_MX_TRANS"."CK_MON_SERVICE_REQUEST" ("SERV_EXEC_STATUS_TS", "AUTHORISATION_ID", "SERVICE_ID", "SERVICE_POD_ID", "DAY_PART_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_VMH_AUDIT_UI1
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_VMH_AUDIT_UI1" ON "STRATOS_MX_TRANS"."CK_VMH_AUDIT" ("SCHM_MSG_CODE", "SCHM_STAN_NU", "SCHM_TRANS_DATETIME", "SCHM_ACQ_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_MMH_AUDIT_UI_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."IDX_CK_MMH_AUDIT_UI_1" ON "STRATOS_MX_TRANS"."CK_MMH_AUDIT" ("SCHM_MSG_CODE", "SCHM_STAN_NU", "SCHM_ACQ_ID", "SCHM_TXN_EXECUTION_SEC_NU", "SCHM_TRANS_DATETIME") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_MMH_AUDIT_UI2
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_MMH_AUDIT_UI2" ON "STRATOS_MX_TRANS"."CK_MMH_AUDIT" ("PMI_ID", "SCHM_STAN_NU", "SCHM_TRANS_DATETIME", "SCHM_MSG_CODE") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_VMH_AUDIT_1
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_VMH_AUDIT_1" ON "STRATOS_MX_TRANS"."CK_VMH_AUDIT" ("SERV_LOG_TS") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_MMH_AUDIT_UI1
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_MMH_AUDIT_UI1" ON "STRATOS_MX_TRANS"."CK_MMH_AUDIT" ("SCHM_MSG_CODE", "SCHM_STAN_NU", "SCHM_TRANS_DATETIME", "SCHM_ACQ_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_DESTINATION_SAF_UI1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."IDX_CK_DESTINATION_SAF_UI1" ON "STRATOS_MX_TRANS"."CK_DESTINATION_SAF" ("SAF_ID", "SAF_PRIORITY_IN", "SAF_ESTIMATED_SEND_TS", "AUTHORISATION_ID", "SAF_STATUS") 
  ;
--------------------------------------------------------
--  DDL for Index CK_TASK_SCHEDULE_IDX1
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."CK_TASK_SCHEDULE_IDX1" ON "STRATOS_MX_TRANS"."CK_TASK_SCHEDULE" ("TASK_TYPE", "TASK_STATUS", "TASK_LAST_UPDATE_TS") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_MMH_AUDIT_UI_2
--------------------------------------------------------

  CREATE INDEX "STRATOS_MX_TRANS"."IDX_CK_MMH_AUDIT_UI_2" ON "STRATOS_MX_TRANS"."CK_MMH_AUDIT" ("PMI_ID", "SCHM_STAN_NU", "SCHM_MSG_CODE") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_MSG_LOG_IDX_UI1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."IDX_CK_MSG_LOG_IDX_UI1" ON "STRATOS_MX_TRANS"."CK_MSG_LOG" ("LOG_TS", "MSG_TYPE", "AUTHORISATION_ID", "SCHEME_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CK_AMH_AUDIT_NET_UI1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRATOS_MX_TRANS"."IDX_CK_AMH_AUDIT_NET_UI1" ON "STRATOS_MX_TRANS"."CK_AMH_AUDIT_NET" ("RTS_ADQ") 
  ;
--------------------------------------------------------
--  Constraints for Table CK_STIP_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_STIP_AUDIT" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_STIP_AUDIT" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_WFT_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_WFT_AUDIT" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_WFT_AUDIT" MODIFY ("SERV_EXEC_SEC_NU" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_WFT_AUDIT" MODIFY ("SERV_EXEC_STATUS_TS" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_WFT_AUDIT" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_WFT_AUDIT" ADD PRIMARY KEY ("AUTHORISATION_ID", "SERV_EXEC_SEC_NU", "SERV_EXEC_STATUS_TS", "SERVICE_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_LIMITS_RULE_ACCUMULATES
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_LIMITS_RULE_ACCUMULATES" ADD PRIMARY KEY ("ENTITY_ID", "FAMILY_ID", "CARDHOLDER_ID", "PROFILE_ID", "LIMIT_CURRENCY", "RULE_CODE", "LIMIT_PERIOD")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_AUTH_ORCHESTRATOR_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_AUTH_ORCHESTRATOR_AUDIT" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AUTH_ORCHESTRATOR_AUDIT" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_AMH_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHEME_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("PMI_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SERV_LOG_TS" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_MSG_CODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_PROCESS_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("ACMS_TRN_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_TRANS_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_STAN_NU" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_ACQ_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_RESPONSE_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("ACMS_RESPONSE_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_DATA_ENTRY_MODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("NETWORK_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("ORIGINAL_AUTH_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_SETTL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_SETTL_CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_LOCAL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_LOCAL_CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_BILLING_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_BILLING_CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("ACMS_AUTH_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_INCOM_MATCHING_KEY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_AUTH_CODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("TERMINAL_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("COMMERCE_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("MSG_DATA" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("CHANNEL_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SERV_EXCEPTION_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SERV_EXCEPTION_TX" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_PROCESSED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_TRANSACTION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("CONSOLIDATED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("SCHM_TXN_EXECUTION_SEC_NU" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" MODIFY ("ENTITY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_TIME_OUT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_TIME_OUT" ADD PRIMARY KEY ("TIMEOUT_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_SAT_AUDIT_NET
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_SAT_AUDIT_NET" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_SAT_AUDIT_NET" MODIFY ("SCHM_MSG_CODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_SAT_AUDIT_NET" MODIFY ("ENTITY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_SAT_AUDIT_NET" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_IMS_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_IMS_AUDIT" MODIFY ("TRACE_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_IMS_AUDIT" MODIFY ("TRACE_TS" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_IMS_AUDIT" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_IMS_AUDIT" MODIFY ("PMI_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_IMS_AUDIT" MODIFY ("PAYMENT_INSTRUMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_IMS_AUDIT" MODIFY ("EXCEPTION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_IMS_AUDIT" MODIFY ("MESSAGE_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_IMS_AUDIT" MODIFY ("ADDITIONAL_DATA" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_IMS_AUDIT" MODIFY ("END_TS" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_IMS_AUDIT" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_IMS_AUDIT" MODIFY ("JSON_REQUEST" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_IMS_AUDIT" MODIFY ("JSON_RESPONSE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_IMS_AUDIT" ADD PRIMARY KEY ("TRACE_ID", "TRACE_TS", "ACTION")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_MET_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_MET_AUDIT" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MET_AUDIT" MODIFY ("PMI_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MET_AUDIT" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_ALERT_SERVICE_TECH_ERROR
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_ALERT_SERVICE_TECH_ERROR" ADD PRIMARY KEY ("ERROR_COUNTER_NU", "DAY_PART_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_MON_SERVICE_REQUEST
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_MON_SERVICE_REQUEST" ADD PRIMARY KEY ("AUTHORISATION_ID", "SERV_EXEC_SEC_NU", "SERV_EXEC_STATUS_TS", "SERVICE_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_VMH_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHEME_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("PMI_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SERV_LOG_TS" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_MSG_CODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_PROCESS_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("ACMS_TRN_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_TRANS_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_STAN_NU" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_ACQ_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_RESPONSE_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("ACMS_RESPONSE_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_DATA_ENTRY_MODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("NETWORK_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("ORIGINAL_AUTH_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_SETTL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_SETTL_CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_LOCAL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_LOCAL_CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_BILLING_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_BILLING_CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("ACMS_AUTH_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_INCOM_MATCHING_KEY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_AUTH_CODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("TERMINAL_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("COMMERCE_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("MCC" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("TRANSACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("COUNTRY_CODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("MSG_DATA" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("CHANNEL_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SERV_EXCEPTION_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SERV_EXCEPTION_TX" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_PROCESSED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_TRANSACTION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("CONSOLIDATED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("SCHM_TXN_EXECUTION_SEC_NU" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT" MODIFY ("ENTITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CK_VMH_AUDIT_NET
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT_NET" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT_NET" MODIFY ("SCHM_MSG_CODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT_NET" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "STRATOS_MX_TRANS"."CK_VMH_AUDIT_NET" MODIFY ("ENTITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CK_CRYPTO_BUSINESS_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_CRYPTO_BUSINESS_AUDIT" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CRYPTO_BUSINESS_AUDIT" MODIFY ("CRYPTO_FUNCTION" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CRYPTO_BUSINESS_AUDIT" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CRYPTO_BUSINESS_AUDIT" MODIFY ("REQUEST_TYPE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CRYPTO_BUSINESS_AUDIT" MODIFY ("CHANNEL_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CRYPTO_BUSINESS_AUDIT" MODIFY ("CRYPTO_RULE_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CRYPTO_BUSINESS_AUDIT" MODIFY ("CRYPTO_CRIT_CODE_EMV" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CRYPTO_BUSINESS_AUDIT" MODIFY ("CRYPTO_CRIT_CODE_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CRYPTO_BUSINESS_AUDIT" MODIFY ("CRYPTO_CRIT_CODE_PMI" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CRYPTO_BUSINESS_AUDIT" MODIFY ("ACMS_TRN_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CRYPTO_BUSINESS_AUDIT" MODIFY ("CRYPTO_TRANSACTION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CRYPTO_BUSINESS_AUDIT" ADD PRIMARY KEY ("AUTHORISATION_ID", "CRYPTO_FUNCTION")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_MSG_LOG
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_MSG_LOG" MODIFY ("SCHEME_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MSG_LOG" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MSG_LOG" MODIFY ("MSG_TYPE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MSG_LOG" ADD PRIMARY KEY ("SCHEME_ID", "AUTHORISATION_ID", "MSG_TYPE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_DESTINATION_SAF
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_DESTINATION_SAF" MODIFY ("SAF_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_DESTINATION_SAF" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_DESTINATION_SAF" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_SAT_OFFLINE_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_SAT_OFFLINE_AUDIT" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_SAT_OFFLINE_AUDIT" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_AUTHORISATION_RULES_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_AUTHORISATION_RULES_AUDIT" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AUTHORISATION_RULES_AUDIT" MODIFY ("PMI_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AUTHORISATION_RULES_AUDIT" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_TDD_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_TDD_AUDIT" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_TDD_AUDIT" MODIFY ("PMI_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_TDD_AUDIT" MODIFY ("SERV_LOG_TS" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_TDD_AUDIT" MODIFY ("SERVICES_DISPATCH_INFO" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_TDD_AUDIT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_TDD_AUDIT" MODIFY ("SERV_EXCEPTION_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_TDD_AUDIT" MODIFY ("SERV_EXCEPTION_TX" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_TDD_AUDIT" MODIFY ("BUSINESS_EXCEPTION_TX" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_TDD_AUDIT" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_MON_SERVICE_RESPONSE
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_MON_SERVICE_RESPONSE" ADD PRIMARY KEY ("AUTHORISATION_ID", "SERV_EXEC_SEC_NU", "SERV_EXEC_STATUS_TS", "SERVICE_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_PARAMETER_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_PARAMETER_AUDIT" ADD CONSTRAINT "CK_PARAMETER_AUDIT_PK" PRIMARY KEY ("TABLE_NAME", "LOGGING_TS", "ACTION_CODE", "TABLE_KEY_DATA", "USER_ID")
  USING INDEX "STRATOS_MX_TRANS"."CK_PARAMETER_AUDIT_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_PIN_CHANGE_LOG
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_PIN_CHANGE_LOG" ADD CONSTRAINT "CK_PIN_CHANGE_LOG_PK" PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX "STRATOS_MX_TRANS"."CK_PIN_CHANGE_LOG_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_MBH_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_MBH_AUDIT" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MBH_AUDIT" MODIFY ("SCHM_TXN_EXECUTION_SEC_NU" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MBH_AUDIT" MODIFY ("PMI_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MBH_AUDIT" MODIFY ("SCHM_MSG_CODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MBH_AUDIT" MODIFY ("SCHM_TRANS_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MBH_AUDIT" MODIFY ("SCHM_STAN_NU" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MBH_AUDIT" MODIFY ("SCHM_FWD_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MBH_AUDIT" MODIFY ("ACMS_TRN_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MBH_AUDIT" MODIFY ("RTS_ADQ" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MBH_AUDIT" ADD PRIMARY KEY ("AUTHORISATION_ID", "SCHM_TXN_EXECUTION_SEC_NU")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table DATABASECHANGELOGLOCK
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."DATABASECHANGELOGLOCK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."DATABASECHANGELOGLOCK" MODIFY ("LOCKED" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."DATABASECHANGELOGLOCK" ADD CONSTRAINT "PK_DATABASECHANGELOGLOCK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_MMH_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHEME_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("PMI_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SERV_LOG_TS" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_MSG_CODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_PROCESS_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("ACMS_TRN_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_TRANS_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_STAN_NU" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_ACQ_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_RESPONSE_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("ACMS_RESPONSE_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_DATA_ENTRY_MODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("NETWORK_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_SESSION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("ORIGINAL_AUTH_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_SETTL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_SETTL_CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_LOCAL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_LOCAL_CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_BILLING_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_BILLING_CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("ACMS_AUTH_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_INCOM_MATCHING_KEY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_AUTH_CODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("TERMINAL_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("COMMERCE_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("MSG_DATA" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("CHANNEL_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SERV_EXCEPTION_CD" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SERV_EXCEPTION_TX" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_PROCESSED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_TRANSACTION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("CONSOLIDATED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("SCHM_TXN_EXECUTION_SEC_NU" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT" MODIFY ("ENTITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CK_SAF_DESTINATION_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_SAF_DESTINATION_SCHEDULE" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_SAF_DESTINATION_SCHEDULE" ADD PRIMARY KEY ("TASK_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_ALERT_ERROR_DETAIL
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_ALERT_ERROR_DETAIL" ADD PRIMARY KEY ("ERROR_COUNTER_NU", "DAY_PART_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_TRANSACTION_COUNTERS
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_TRANSACTION_COUNTERS" MODIFY ("PMI_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_TRANSACTION_COUNTERS" MODIFY ("PMI_SEC_NU" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_TRANSACTION_COUNTERS" ADD PRIMARY KEY ("PMI_ID", "PMI_SEC_NU")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_WFT_RESEND_LOG
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_WFT_RESEND_LOG" ADD PRIMARY KEY ("SERVICE_ID", "AUTHORISATION_ID", "SERV_ORDER_EXEC_NU")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_SAF_SENDER_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_SAF_SENDER_SCHEDULE" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_SAF_SENDER_SCHEDULE" ADD PRIMARY KEY ("TASK_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_SAT_LOG
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_SAT_LOG" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_SAT_LOG" ADD PRIMARY KEY ("AUTHORISATION_ID", "MSG_TYPE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_USER_TOKEN
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_USER_TOKEN" MODIFY ("ENTITY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_USER_TOKEN" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_USER_TOKEN" MODIFY ("USER_SESION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_USER_TOKEN" ADD PRIMARY KEY ("ENTITY", "USER_ID", "USER_SESION_NUMBER")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_MON_TRANSACTION_QUALITY
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_MON_TRANSACTION_QUALITY" ADD PRIMARY KEY ("DAY_PART_ID", "SERVICE_ID", "AUTHORISATION_ID", "SERV_EXEC_SEC_NU", "SYS_ENT_TS")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_FVS_LOG
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_FVS_LOG" MODIFY ("MSG_KEY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_FVS_LOG" MODIFY ("MSG_TYPE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_FVS_LOG" ADD PRIMARY KEY ("MSG_KEY", "MSG_TYPE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_AMH_AUDIT_NET
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT_NET" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT_NET" MODIFY ("SCHM_MSG_CODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT_NET" MODIFY ("ENTITY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_AMH_AUDIT_NET" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_DRAWNDOWN_CONTROL
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_DRAWNDOWN_CONTROL" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table DATABASECHANGELOG
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."DATABASECHANGELOG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."DATABASECHANGELOG" MODIFY ("AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."DATABASECHANGELOG" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."DATABASECHANGELOG" MODIFY ("DATEEXECUTED" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."DATABASECHANGELOG" MODIFY ("ORDEREXECUTED" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."DATABASECHANGELOG" MODIFY ("EXECTYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CK_CVS_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_CVS_AUDIT" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CVS_AUDIT" MODIFY ("ENTITY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CVS_AUDIT" MODIFY ("INT_MTI" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CVS_AUDIT" MODIFY ("SERV_LOG_TS" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CVS_AUDIT" MODIFY ("PMI_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CVS_AUDIT" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_MMH_AUDIT_NET
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT_NET" MODIFY ("AUTHORISATION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT_NET" MODIFY ("SCHM_MSG_CODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT_NET" ADD PRIMARY KEY ("AUTHORISATION_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "STRATOS_MX_TRANS"."CK_MMH_AUDIT_NET" MODIFY ("ENTITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CK_MQ_RESEND_LOG
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_MQ_RESEND_LOG" ADD PRIMARY KEY ("EXCHANGE", "AUTHORISATION_ID", "SERV_ORDER_EXEC_NU")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_LIMIT_AUDIT
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_LIMIT_AUDIT" ADD CONSTRAINT "CK_LIMIT_AUDIT_PK" PRIMARY KEY ("AUTHORISATION_ID", "ACTION_CODE", "VALIDATION_TYPE")
  USING INDEX "STRATOS_MX_TRANS"."CK_LIMIT_AUDIT_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_CONNECTION_LOG
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_CONNECTION_LOG" MODIFY ("CONN_LOG_TS" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CONNECTION_LOG" MODIFY ("SCHEME_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CONNECTION_LOG" MODIFY ("CHANNEL_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CONNECTION_LOG" MODIFY ("CONNECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CONNECTION_LOG" MODIFY ("ACTION_TYPE_IND" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CONNECTION_LOG" MODIFY ("CONNECTION_MODE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CONNECTION_LOG" MODIFY ("ENDPOINT_DIR" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CONNECTION_LOG" MODIFY ("ENDPOINT_PORT" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CONNECTION_LOG" MODIFY ("ACMS_BRIDGE_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_CONNECTION_LOG" ADD PRIMARY KEY ("CONN_LOG_TS", "SCHEME_ID", "CHANNEL_ID", "CONNECTION_ID", "ACTION_TYPE_IND")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_INSTRUMENT_HOT_CARD
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_INSTRUMENT_HOT_CARD" MODIFY ("PMI_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_INSTRUMENT_HOT_CARD" MODIFY ("WHEN_ADDED" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_INSTRUMENT_HOT_CARD" MODIFY ("ENTITY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_INSTRUMENT_HOT_CARD" ADD PRIMARY KEY ("PMI_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_SAF_STATUS
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_SAF_STATUS" ADD PRIMARY KEY ("ENTITY", "SAF_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_BALANCES
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_BALANCES" MODIFY ("ENTITY" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_BALANCES" MODIFY ("ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_BALANCES" MODIFY ("LAST_UPDATE" NOT NULL ENABLE);
  ALTER TABLE "STRATOS_MX_TRANS"."CK_BALANCES" ADD CONSTRAINT "CK_BALANCES_PK" PRIMARY KEY ("ENTITY", "ACCOUNT_ID")
  USING INDEX "STRATOS_MX_TRANS"."CK_BALANCES_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CK_TASK_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "STRATOS_MX_TRANS"."CK_TASK_SCHEDULE" ADD PRIMARY KEY ("TASK_ID")
  USING INDEX  ENABLE;
